#Site settings
title: fatcafacil.com
email: sales@complexless.com 
layout: default.html
description: > # this means to ignore newlines until "baseurl:"
  Documentación FatcaFácil.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.fatcafacil.com" # the base hostname & protocol for your site
twitter_username: complexless
twitter_text: "Documentación de FatcaFacil"
github_username:  complexless

# Lista de Colaboradores
collaborators:
  secretaria_salud:
    title: "ComplexLess"
    site: "http://complexless.com"
    logo_url: ""

# Build settings
markdown: kramdown
gems: ['jekyll-redirect-from']
jekyll_timeago:
  depth: 1 # Level of detail
  today: 'hoy'
  yesterday: 'ayer'
  tomorrow: 'mañana'
  and: 'y'
  suffix: ''
  prefix: 'hace'
  suffix_future: 'en'
  prefix_future: ''
  years: 'años'
  year: 'año'
  months: 'meses'
  month: 'mes'
  weeks: 'semanas'
  week: 'semana'
  days: 'dias'
  day: 'dia'
